# Generated by Django 4.1.2 on 2022-12-04 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_remove_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
