# Generated by Django 4.1.2 on 2022-11-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='entry_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='diaryentry',
            old_name='entry_title',
            new_name='title',
        ),
    ]
