# Generated by Django 4.1.2 on 2022-11-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_entry_text_diaryentry_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
