# Generated by Django 4.1.2 on 2022-12-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_diaryentry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
    ]
