# Generated by Django 4.1.2 on 2022-12-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_diaryentry_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='sentiment_label',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
