# Generated by Django 4.1.4 on 2022-12-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_diaryentry_sentiment_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='\u200b/static/'),
        ),
    ]
