# Generated by Django 4.1.4 on 2022-12-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_diaryentry_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='profile_image',
            new_name='image',
        ),
    ]
